export interface ProductUpdate {
    id: 0,
    productType: string,
    userId: number,
	name: string,
    description: string,
    sku: string,
    quantity: number,
    price: number,
    category:number,
  //  color:string,
    isActive: number,
    madeInusa: string,
    wrinkleFreeknit: string,
    regularFit: string,
    slimFit: string,
    looseFit: string,
    materialContent:string,
    careInstructions:string
};
